---
title: "Assigment3"
format: html
editor: visual
language: nb.yaml
---

```{r}
#| label: setup
#| echo: false
library(tidyverse)
library(tidyselect)
library(lubridate)
library(PxWebApiData)
library(flextable)
```

## Innledning

## Henta data fra SSB

```{r}
unemp99to02 <- ApiData(
  "http://data.ssb.no/api/v0/en/table/10540",
  # Have not been able to specify more complex regions
  Region = list("11*"),
  Tid = c(paste(
    rep(1999:2002, each = 12), 
    "M",
    sprintf("%02d", 1:12), 
    sep = "")
    )
  )
```

```{r}
#Get more info about table
ApiData(
"http://data.ssb.no/api/v0/en/table/03321",
returnApiQuery = TRUE
) 
```

```{r}
#| cache: true
#Bokommuner Haugalandet
pend_00_22_ssb_boHland <- PxWebApiData::ApiData12(
  urlToData = as.character(03321),
  ArbstedKomm = list("*"),
  Bokommuen = c("1106", "1135", "1145", "1146", "1149", "1154", "1159", "1160", "4611", "4612", "1211", "1216"),
  Tid = as.character(2000:2022))
```

```{r}
#| cache: true
#Arbeidskommuner Haugalandet
pend_00_22_ssb_arbHland <- PxWebApiData::ApiData12(
  urlToData = as.character(03321),
  ArbstedKomm = c("1106", "1135", "1145", "1146", "1149", "1154", "1159", "1160", "4611", "4612", "1211", "1216"),
  Bokommuen = list("*"),
  Tid = as.character(2000:2022)
)
```

```{r}
#Lager egen redusert versjon av satasettet(arbeidskommuner)
pend_00_22_arbHland <- pend_00_22_ssb_arbHland |> select(arb_kom = arbeidsstedskommune, bo_kom = bostedskommune, aar = 4, pendlere = value)
```

```{r}
#Lager egen redusert versjon av satasettet(bokommuner)
pend_00_22_boHland <- pend_00_22_ssb_boHland |> select(arb_kom = arbeidsstedskommune, bo_kom = bostedskommune, aar = 4, pendlere = value)
```

```{r}
# med hensyn på arbeidskommune
pend_00_22_arbHland$arb_kom <- fct(pend_00_22_arbHland$arb_kom)
pend_00_22_boHland$bo_kom <- fct(pend_00_22_boHland$bo_kom)
pend_00_22_boHland$arb_kom <- fct(pend_00_22_boHland$arb_kom)

pend_00_22_arbHland$arb_kom <- fct_collapse(pend_00_22_arbHland$arb_kom, Haugesund = "Haugesund",
                                      Sauda = "Sauda",
                                      Bokn = "Bokn",
                                      Tysvær = "Tysvær",
                                      Karmøy = "Karmøy", 
                                      Etne = c("Etne", "Etne (-2019)"), 
                                      Sveio = c("Sveio", "Sveio (-2019)"), 
                                      
                                
                                      Vindafjord_Ølen = c("Vindafjord", "Vindafjord (1965-2005)", "Ølen (2002-2005)"),
                                      other_level = "Andre")

#med hensyn på arb kommune
pend_00_22_arbHland$bo_kom <- fct_collapse(pend_00_22_arbHland$bo_kom, Haugesund = "Haugesund",
                                      Sauda = "Sauda",
                                      Bokn = "Bokn",
                                      Tysvær = "Tysvær",
                                      Karmøy = "Karmøy", 
                                      Etne = c("Etne", "Etne (-2019)"), 
                                      Sveio = c("Sveio", "Sveio (-2019)"), 
                                      
                                
                                      Vindafjord_Ølen = c("Vindafjord", "Vindafjord (1965-2005)", "Ølen (2002-2005)"),
                                      other_level = "Andre")

####################



pend_00_22_boHland$arb_kom <- fct_collapse(pend_00_22_boHland$arb_kom, Haugesund = "Haugesund",
                                      Sauda = "Sauda",
                                      Bokn = "Bokn",
                                      Tysvær = "Tysvær",
                                      Karmøy = "Karmøy", 
                                      Etne = c("Etne", "Etne (-2019)"), 
                                      Sveio = c("Sveio", "Sveio (-2019)"), 
                                      
                                
                                      Vindafjord_Ølen = c("Vindafjord", "Vindafjord (1965-2005)", "Ølen (2002-2005)"),
                                      other_level = "Andre")

#med hensyn på bo kommune
pend_00_22_boHland$bo_kom <- fct_collapse(pend_00_22_boHland$bo_kom, Haugesund = "Haugesund",
                                      Sauda = "Sauda",
                                      Bokn = "Bokn",
                                      Tysvær = "Tysvær",
                                      Karmøy = "Karmøy", 
                                      Etne = c("Etne", "Etne (-2019)"), 
                                      Sveio = c("Sveio", "Sveio (-2019)"), 
                                      
                                
                                      Vindafjord_Ølen = c("Vindafjord", "Vindafjord (1965-2005)", "Ølen (2002-2005)"),
                                      other_level = "Andre")






```

```{r}
dim(pend_00_22_boHland)
```

```{r}
# eval: false
pend_00_22_arbHland <- pend_00_22_arbHland |>
group_by(aar, bo_kom, arb_kom) |>
summarise(pendlere = sum(pendlere), .groups = "drop")

```

```{r}
#Har vi gjort ting riktig skal vi ha:
dim(pend_00_22_arbHland)
```

```{r}
print(pend_00_22_boHland, n = 5)

```

```{r}
# nå gjør vi det samme for bo
# eval: false
pend_00_22_boHland <- pend_00_22_boHland |>
group_by(aar, arb_kom, bo_kom) |>
summarise(pendlere = sum(pendlere), .groups = "drop")
```

```{r}
pmat_long <- pend_00_22_arbHland |> 
  full_join(
    pend_00_22_boHland,
    by = c("aar", "arb_kom", "bo_kom", "pendlere")
  ) |> 
  ungroup() 
dim(pmat_long)
```

```{r}
pmat_long |> 
  head(n = 5)
```

```{r}
pmat_long <- pmat_long |> 
  group_by(bo_kom, aar) |> 
  mutate(
    bo_prosent = round((pendlere/sum(pendlere))*100, digits = 1)
  ) |> 
  ungroup()
pmat_long <- pmat_long |> 
  group_by(arb_kom, aar) |> 
  mutate(
    arb_prosent = round((pendlere/sum(pendlere))*100, digits = 1)
  )
```

```{r}
ordKom <- c("bo_kom" , "Haugesund", "Karmøy", "Tysvær",
"Sveio", "Bokn", "Vindafjord_Ølen", "Sauda",
"Etne", "Andre")
# Filtrer datasettet for år 2000 og transformer det til en bredere format
p2000 <- pmat_long %>%
  filter(aar == 2000) %>%
  select(bo_kom, arb_kom, pendlere) %>%
  pivot_wider(names_from = arb_kom, values_from = pendlere, names_sort = TRUE) %>%
  mutate(bo_kom = factor(bo_kom, levels = ordKom)) %>%
  arrange(bo_kom) %>%
  select(
    "Bo kom. \\ Arb. kom" = bo_kom,
    all_of(ordKom),
    )

# Skriv ut 'p2000' for å bekrefte endringene
print(p2000)

```

```{r}
#| label: tbl-p2000
#| tbl-cap: "Pendlematrise for Haugalandet år 2000."
p2000 |>
flextable() |>
# a4 8.268 in - 1 in left margin - 1 in right margin = 6.268 in
fit_to_width(max_width = 6.268, inc = 1L, max_iter = 20, unit = "in") |>
line_spacing(space = 0,
part = "body"
) %>%
hrule(rule = "exact") %>%
height_all(height = 5, part = "all", unit = "mm") |>
padding(padding.top = 1, padding.bottom = 2, part = "all") %>%
theme_booktabs()
```
